# fly.toml app configuration file generated for funklist on 2026-09-28T19:43:47Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'funklist'
primary_region = 'ord'

[build]

[env]
  NODE_ENV = 'production'
  TRUST_PROXY = '1'
  APP_URL = 'https://funklist.fly.dev'

[[mounts]]
  source = 'funklist_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
